### PR TITLE
Adding authentication APIs

### PR DESCRIPTION
**Pull request by JohnsonMasino**
Adding authentication APIs to start with.
Built User creation, login, logout and reset password features.

### CODE REVIEW

**Review by MichealCodez — COMMENTED** [review]
Add a gitignore to ignore the venv folder

**Comment by JohnsonMasino** [comment]
Oh yeah !
On it.

**Comment by JohnsonMasino** [comment]
gitignore file added. Working on an explanatory readme file

**Review by MichealCodez — APPROVED** [review]
good

**Pull request merged**
